$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$migrationDir = Join-Path $repoRoot 'supabase\migrations'
$outDir = Join-Path $repoRoot 'out\supabase'
$outFile = Join-Path $outDir 'spike-0001-0004.sql'

$sources = @(
  '0001_ops_private_and_public_core.sql',
  '0002_rls_realtime.sql',
  '0003_mm_raw_audit_and_shipment.sql',
  '0004_work_item_shipment_fk.sql'
)

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$header = @(
  '-- Generated by scripts/prepare-spike-supabase-bundle.ps1',
  '-- Purpose: combine spike migrations 0001-0004 into a single SQL file',
  '-- Safe usage: review before running on a shared project',
  "-- Source directory: $migrationDir",
  ''
)

$content = New-Object System.Collections.Generic.List[string]
$header | ForEach-Object { [void]$content.Add($_) }

foreach ($name in $sources) {
  $path = Join-Path $migrationDir $name
  if (-not (Test-Path $path)) {
    throw "Missing migration file: $path"
  }

  [void]$content.Add("-- >>> BEGIN $name")
  Get-Content -LiteralPath $path | ForEach-Object { [void]$content.Add($_) }
  [void]$content.Add("-- <<< END $name")
  [void]$content.Add('')
}

Set-Content -LiteralPath $outFile -Value $content -Encoding UTF8
Write-Output "Wrote $outFile"
